/**
 * This script will delete all Subscriptions that were generated by the bot.
 */

import * as dotenv from 'dotenv'
dotenv.config()
import { MedplumClient } from "@medplum/core";
import fetch from "node-fetch";
import { PROJECT_TAG_CODE_BOT, PROJECT_TAG_SYSTEM } from '../../common/common.mjs';

async function main() {
  if (process.env.MEDPLUM_CLIENT_ID === undefined) throw new Error("MEDPLUM_CLIENT_ID environment variable is missing");
  if (process.env.MEDPLUM_CLIENT_SECRET === undefined) throw new Error("MEDPLUM_CLIENT_SECRET environment variable is missing");
  const medplum = new MedplumClient({ fetch: fetch });
  await medplum.startClientLogin(process.env.MEDPLUM_CLIENT_ID, process.env.MEDPLUM_CLIENT_SECRET);
  const existing_subscriptions = await medplum.searchResources("Subscription");
  for (const sub of existing_subscriptions) {
    if (sub.meta?.tag?.some(v => v.system === PROJECT_TAG_SYSTEM && v.code === PROJECT_TAG_CODE_BOT)){
      await medplum.deleteResource("Subscription", sub.id!);
    }
  }
}

main();